# model paths:
#   zh -> en
#   zh -> de
#         en -> es
#         en -> fr
#         en -> it
#         en -> ja
#         en -> ru
#               es -> en
#               fr -> en
#               it -> en
#               ja -> en
#               ru -> en
#         en ........ en -> zh
#         de -> zh

# translation paths:
#     1. zh -> en -> zh
#     2. zh -> de -> zh
#     3. zh -> en -> es -> en -> zh
#     4. zh -> en -> fr -> en -> zh
#     5. zh -> en -> it -> en -> zh
#     6. zh -> en -> ja -> en -> zh
#     7. zh -> en -> ru -> en -> zh

model_paths:
    zh_en: ./Helsinki-NLP/opus-mt-zh-en/
    zh_de: ./Helsinki-NLP/opus-mt-zh-de/
    en_es: ./Helsinki-NLP/opus-mt-en-es/
    en_fr: ./Helsinki-NLP/opus-mt-en-fr/
    en_it: ./Helsinki-NLP/opus-mt-en-it/
    en_ja: ./Helsinki-NLP/opus-mt-en-ja/
    en_ru: ./Helsinki-NLP/opus-mt-en-ru/
    es_en: ./Helsinki-NLP/opus-mt-es-en/
    fr_en: ./Helsinki-NLP/opus-mt-fr-en/
    it_en: ./Helsinki-NLP/opus-mt-it-en/
    ja_en: ./Helsinki-NLP/opus-mt-ja-en/
    ru_en: ./Helsinki-NLP/opus-mt-ru-en/
    en_zh: ./Helsinki-NLP/opus-mt-en-zh/
    de_zh: ./Helsinki-NLP/opus-mt-de-ZH/

translation_tracks: [
    [zh_en, en_zh],
    [zh_de, de_zh],
    [zh_en, en_es, es_en, en_zh],
    [zh_en, en_fr, fr_en, en_zh],
    [zh_en, en_it, it_en, en_zh],
    [zh_en, en_ja, ja_en, en_zh],
    [zh_en, en_ru, ru_en, en_zh]
]

active_tracks: [0]